import type { NextPage } from 'next';
import Head from 'next/head';
import Calendar from 'components/Calendar';
import Datepicker from 'components/Datepicker';
// import Flatpicker from 'components/Flatpicker';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-5-0">
        {/* <div className="mt-2-0">
          <Calendar />
        </div> */}
        <div className="mt-2-0">
          <Datepicker />
        </div>
        <div className="mt-2-0">{/* <Flatpicker /> */}</div>
        <div className="mt-2-0">{/* <input type="date" /> */}</div>
      </main>
    </div>
  );
};

export default Home;
