import type { NextPage } from 'next';
import Head from 'next/head';
import Calendar from 'components/Calendar';
import Datepicker from 'components/Datepicker';
import Cropper from 'components/Cropper';
import CropperV2 from 'components/CropperV2';
import { useRef, useState } from 'react';
// import Flatpicker from 'components/Flatpicker';

const Home: NextPage = () => {
  const [croppedImg, setCroppedImg] = useState<any>();
  const [open, setOpen] = useState<boolean>(false);
  const [img, setImg] = useState<string>('/images/profile.png');
  const [baseImg, setBaseImg] = useState<string>('/images/profile.png');

  console.log(img);

  return (
    <div>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-5-0">
        <div className="mt-2-0">
          <p className="mb-2-0">Datepicker</p>
          <Datepicker />
        </div>
        <div className="mt-2-0">
          <p className="mb-2-0">Cropper</p>
          <Cropper />
        </div>
        <div className="mt-2-0">
          <p className="mb-2-0">Cropper v2</p>
          <CropperV2
            img={img}
            setImg={setImg}
            baseImg={baseImg}
            setBaseImg={setBaseImg}
          />
          <div className="rounded-50-percent overflow-hidden w-fit my-5-0 mx-3-0">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={img ? img : baseImg} alt="" />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
