import type { NextPage } from 'next';
import Head from 'next/head';
import Datepicker from 'components/Datepicker';
import Cropper from 'components/Cropper';
import { useState } from 'react';
import Image from 'next/image';

const Home: NextPage = () => {
  const [img, setImg] = useState('/images/test.jpg');

  const handleImg = (newVal: string): void => {
    setImg(newVal);
  };

  return (
    <div>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-5-0">
        <div className="mt-2-0">
          <p className="mb-2-0">Datepicker</p>
          <Datepicker />
        </div>

        <div className="mt-2-0">
          <p className="mb-2-0">Cropper </p>
          <Cropper img={img} handleImg={handleImg} />
          <div className="rounded-50-percent overflow-hidden w-fit my-5-0 mx-3-0">
            <div className="h-36-0 w-36-0">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <Image
                src={img}
                alt=""
                layout="responsive"
                width="100%"
                height="100%"
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
